// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 1,
    title: "Basmati Rice",
    description: "Buy your fresh basmati rice",
    price: 69,
    coverImg: "basmati.jpg",
    location: "Online",
  },
  {
    id: 2,
    title: "White Rice",
    description: "Healthy white rice for sale",
    price: 136,
    coverImg: "rice.jpg",
    location: "Online",
  },
  {
    id: 3,
    title: "Corn",
    description: "Fesh corn from the farm",
    price: 136,
    coverImg: "corn.jpg",
    location: "Online",
  },
  {
    id: 4,
    title: "Wheat",
    description: "Fresh Wheat ",
    price: 136,
    coverImg: "wheat.jfif",
    location: "Online",
  },
  {
    id: 5,
    title: "Olive Oil",
    description: "Buy your olive oil",
    price: 69,
    coverImg: "olive-oil.jpg",
    location: "Online",
  },
  {
    id: 6,
    title: "Palm Oil",
    description: "Healthy palm oil for sale",
    price: 136,
    coverImg: "palm-oil.jfif",
    location: "Online",
  },
  {
    id: 7,
    title: "Soya Oil",
    description: "Fesh soya oil for sale",
    price: 136,
    coverImg: "Soya-oil.jpg",
    location: "Online",
  },
  {
    id: 8,
    title: "Vegetable Oil",
    description: "Buy your pure vegetable oil",
    price: 136,
    coverImg: "veg-oil.png",
    location: "Online",
  },
  {
    id: 9,
    title: "Banana",
    description: "Buy your fresh banana",
    price: 69,
    coverImg: "banana.jfif",
    location: "Online",
  },
  {
    id: 10,
    title: "Apples",
    description: "Buy your fresh apples",
    price: 136,
    coverImg: "apples.jfif",
    location: "Online",
  },
  {
    id: 11,
    title: "Brown Rice",
    description: "Fesh corn from the farm",
    price: 136,
    coverImg: "brown_rice.jfif",
    location: "Online",
  },
  {
    id: 12,
    title: "Wheat",
    description: "Fresh Wheat ",
    price: 136,
    coverImg: "wheat.jfif",
    location: "Online",
  },
  // {
  //   id: 13,
  //   title: "Basmati Rice",
  //   description: "Buy your fresh basmati rice",
  //   price: 69,
  //   coverImg: "basmati.jpg",
  //   location: "Online",
  // },
  // {
  //   id: 14,
  //   title: "White Rice",
  //   description: "Healthy white rice for sale",
  //   price: 136,
  //   coverImg: "rice.jpg",
  //   location: "Online",
  // },
  // {
  //   id: 15,
  //   title: "Corn",
  //   description: "Fesh corn from the farm",
  //   price: 136,
  //   coverImg: "corn.jpg",
  //   location: "Online",
  // },
  // {
  //   id: 16,
  //   title: "Wheat",
  //   description: "Fresh Wheat ",
  //   price: 136,
  //   coverImg: "wheat.jfif",
  //   location: "Online",
  // },
];
