// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 1,
    title: "Victoria Island, Lagos",
    description: "The 39th Tower,39, Simpson Street, Ikoyi, Lagos.",
    price: 69,
    coverImg: "vi.jpg",
    location: "Online",
  },
  {
    id: 2,
    title: "Surulere, Lagos",
    description: "3 Oniru Street, Stadium, Surulere, Lagos",
    price: 136,
    coverImg: "surulere.jpg",
    location: "Online",
  },
  {
    id: 3,
    title: "Mumbai, India",
    description: "The 39th Tower,39, Simpson Street, Mumbai, India.",
    price: 136,
    coverImg: "new-delhi.webp",
    location: "Online",
  },
  {
    id: 4,
    title: "Los Angeles, CA",
    description: "39th Tower,39, Simpson Street, Mumbai, India",
    price: 136,
    coverImg: "la.jfif",
    location: "Online",
  },
  {
    id: 5,
    title: "Brooklyn, New York",
    description: "39th Tower,39, Simpson Street, Mumbai, India",
    price: 69,
    coverImg: "ny.jfif",
    location: "Online",
  },
  {
    id: 6,
    title: "Oxford, London",
    description: "40th Tower,39, Simpson Street, London, UK",
    price: 136,
    coverImg: "london.jfif",
    location: "Online",
  },
  {
    id: 7,
    title: "New Delhi",
    description: "39th Tower,39, Simpson Street, New Delhi. ",
    price: 136,
    coverImg: "new-delhi.webp",
    location: "Online",
  },
  {
    id: 8,
    title: "Abuja, NG",
    description: "39th Tower,39, Simpson Street, Abuja, Nigeria",
    price: 136,
    coverImg: "vi.jpg",
    location: "Online",
  },
  {
    id: 9,
    title: "Cape Town",
    description: "Witwatersand, CE Ave, Cape Town, South Africa",
    price: 69,
    coverImg: "cape-town.jpg",
    location: "Online",
  },
  {
    id: 10,
    title: "Dublin",
    description: "University College Road, Simpson Street, Dublin, Ireland",
    price: 136,
    coverImg: "london.jfif",
    location: "Online",
  },
  {
    id: 11,
    title: "Toronto, Canada",
    description: "Aubrey Graham Plaza, Toronto, Canada",
    price: 136,
    coverImg: "toronto.webp",
    location: "Online",
  },
  {
    id: 12,
    title: "Nairobi",
    description: "39th Tower,39, Simpson Street, Nairobi, Kenya",
    price: 136,
    coverImg: "nairobi.jfif",
    location: "Online",
  },
];
